### ISSUE TITLE
Chapter 08 - nil pointer exception due to removed monkey patching?

### ISSUE THREAD

**Issue by midnightrun** [PacktPublishing/Hands-On-Dependency-Injection-in-Go#2]
Hi,
I am reading Chapter 08 and tried to refactor the code from Chapter 07 with the mentioned technique of Config Injection. After applying those changes to the `data` package, I am running into nil pointer exception.

I compared my happy path test from chapter 07 with the example code of 08 and recognized that the `defer` was removed:

Chapter 07
https://github.com/PacktPublishing/Hands-On-Dependency-Injection-in-Go/blob/master/ch07/acme/internal/modules/data/data_test.go#L31

Chapter 08
https://github.com/PacktPublishing/Hands-On-Dependency-Injection-in-Go/blob/master/ch07/acme/internal/modules/data/data_test.go#L31

I could not find the text in the book mentioning it to remove it and how I understood monkey patching the `defer` is needed to set the original function back to its initial state.

Would be great if you @corsc could show/explain to me how this could be fixed :) 

Thanks a lot!

**Comment by midnightrun** [comment]
For completeness here my `go test` output:

```shell
--- FAIL: TestSave_happyPath (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x105d678]

goroutine 4 [running]:
testing.tRunner.func1(0xc000126100)
	/usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:830 +0x388
panic(0x130f380, 0x15f93f0)
	/usr/local/Cellar/go/1.12/libexec/src/runtime/panic.go:522 +0x1b5
github.com/PacktPublishing/Hands-On-Dependency-Injection-in-Go/ch07/acme/internal/modules/data.TestSave_happyPath(0xc000126100)
	/Users/x/source/Hands-On-Dependency-Injection-in-Go/ch07/acme/internal/modules/data/data_test.go:36 +0x232
testing.tRunner(0xc000126100, 0x1384140)
	/usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:916 +0x357
exit status 2
FAIL	github.com/PacktPublishing/Hands-On-Dependency-Injection-in-Go/ch07/acme/internal/modules/data	0.017s
```

**Comment by corsc** [comment]
Sorry for the delay @midnightrun, notifications on GH seem to get missed.

Would you mind posting the test code as well?

Beside that, yes, the `defer` is there to restore the previous database pool after the test.
I am not sure but I believe the reason I didn't bother with `defer` for chapter 8 is that there is no database pool to restore.  
In chapter 7, the database pool was dependent on the global config and as such was somewhat "auto-initialized", in chapter 8 there is no dependence and therefore no "auto-initialization".
Leaving the original `defer` would arguably be cleaner and would not be detrimental.
